#!/usr/bin/env bash
# Script that configures the webservers to run Nginx as nginx listening on port 8080 

# Edit the nginx.conf file to run nginx as nginx user
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf

# Edit the default site configuration file to listen on all active IPs on port 8080
sed -i 's/80/8080/g' /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf

# apache may interfere with nginx so kill the process if it is running
pkill apache2

# Start nginx service
sudo -u nginx service nginx start
